### ISSUE TITLE
New website release

### ISSUE THREAD

**Issue by sirodoht** [nwspk/web#31]
* [x] Add continuous deployment for new-design branch
* [x] Fix font loading
* [x] Sign up as a member page
* [x] User profile page
* [x] Add continuous deployment for production
* [x] Change canonical url to newspeak.house
* [x] Figure out why database reads are extremely slow
* [x] Document how to access server + how it's set up

**Comment by edsaperia** [comment]
- [ ] centre picture %div.center-img{:style => "background-image: url(#{image_path "newspeak%20house%20elevation.png"})"}
- [ ] events styling
- [ ] fixed position nav
- [ ] profile-pic size & padding
- [ ] profile-text quote style
- [ ] footer padding
- [ ] table padding
- [ ] current residents & fellows picture sizes

**Comment by edsaperia** [comment]
so close!!

**Comment by edsaperia** [comment]
- [ ] Why are some images not showing?
- [ ] Make pastoral board email
- [ ] feedback form
- [ ] application form
- [ ] mobile header
