### ISSUE TITLE
Can't subscribe to event calendar

### ISSUE THREAD

**Issue by CGiattino** [nwspk/web#40]
Hi,

When I click the link on this page (https://newspeak.house/events), which goes to webcal://newspeak.house/api/events.ics, nothing seems to happen. I'm accessing using Chrome Version 115.0.5790.170 (current version) on a Macbook Air (M1, 2020).

Thanks,
Charlie

**Comment by sirodoht** [comment]
Hi Charlie!

As a possible quick solution, may I suggest to use another browser to test this?

What happens in my computer (macOS + Firefox) is that my Calendar application offers to read this link:

<img width="562" alt="image" src="https://github.com/nwspk/web/assets/553444/3ca2e8be-fe5e-425d-a9ca-12f8b33e4f89">

You can also visit this link using the http protocol, in which case it should download the ICS file, which you can manually import into your calendar:
https://newspeak.house/api/events.ics
