### ISSUE TITLE
Can't upload user images

### ISSUE THREAD

**Issue by edsaperia** [nwspk/web#41]
When uploading user avatars from the admin dashboard, I get the error "Avatar Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: You must have ImageMagick or GraphicsMagick installed"

When uploading user avatars from the user account page, it reloads and no image has been uploaded.

**Comment by edsaperia** [comment]
![ted](https://github.com/nwspk/web/assets/5703915/d117d40f-550e-4fc0-b3ae-a95ca652408a)
here's the image I tried with, in case it's anything to do with that!

**Comment by frabcus** [comment]
@edsaperia what's the admin dashboard? The instructions say just to upload a file to the directory in this GitHub repo - did you do that, and which file https://github.com/nwspk/web#images?

Also where did you see the error? Can you share a screenshot, or a link to a failing Github Actions deploy (I can't see one)?

**Comment by edsaperia** [comment]
There's an admin dashboard I have access to for e.g. managing the event database and the users database.

Users who have the status "fellow" are published in various places - website, email - but I haven't been able to create those users and give them avatars. I could put them up on the site in a static way but I hoped this problem would be solved sooner than now, and it would mean they're not put into the email system.

Here's a screenshot of the error:

![image](https://github.com/nwspk/web/assets/5703915/fb45e61f-5129-4ecc-907d-b3eaf372e648)

**Comment by sirodoht** [comment]
I think this is fixed. There was an ImageMagick system-level dependency missing.
